"""empty message

Revision ID: 38a31788a05a
Revises: ad29ca906c41
Create Date: 2021-08-30 09:14:52.934101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a31788a05a'
down_revision = 'ad29ca906c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
